### ISSUE TITLE
Part 6, typos, improvements

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/AspNetCore-StarChartAPI#43]
**Part/module:** [Create CelestialObjectController's Post, Put, Patch, and Delete Actions](https://app.pluralsight.com/projects/create-a-starchart-web-api-using-asp-net-core/create-celestialobjectcontroller-s-post-put-patch-and-delete-actions)

**issues:**

- [x] _6.1 Create the Create Method:_ "The newly created CelestialObject" ➡️ "The provided CelestialObject"
- [x] _6.1 Create the Create Method:_ "NotFound" ➡️"NotFound()" ([arguable, maybe a nofix](https://github.com/pluralsight-projects/AspNetCore-StarChartAPI/issues/40))
- [x] _6.2 Create Update Action:_ "OrbitedObject" ➡️ "OrbitedObjectId"
- [x] _6.2 Create Update Action:_ "NotFound" ➡️"NotFound()" ([arguable, maybe a nofix](https://github.com/pluralsight-projects/AspNetCore-StarChartAPI/issues/40))
- [x] _6.2 Create Update Action:_ "NoContent" ➡️"NoContent()" ([arguable, maybe a nofix](https://github.com/pluralsight-projects/AspNetCore-StarChartAPI/issues/40))

@EricJFisher

**Comment by EricJFisher** [comment]
All corrections made, Thanks for the feedback!
